### ISSUE TITLE
Build time drastically increases with preserveModules: true

### ISSUE THREAD

**Issue by Razenpok** [laynezh/vite-plugin-lib-assets#95]
Sorry, I'm not able to figure out a minimal repro.

https://github.com/refined-prun/refined-prun/tree/c9066d714516c7b6f79dbdbff41c02c24bd9af19

Build times with `pnpm build`:

- No changes: 5.46s
- With `rollupOptions.output.preserveModules: false`: 2.03s
- Removed `libAssetsPlugin` from plugins: 2.07s
- With `rollupOptions.output.preserveModules: false` and removed `libAssetsPlugin`: 1.89s

As far as I can see, `vite-plugin-lib-assets` really doesn't like the fact that I set `rollupOptions.output.preserveModules` to `true`

**Comment by Razenpok** [comment]
There are only 4 asset files in the project, and the build time goes down if I remove these lines that reference them

https://github.com/refined-prun/refined-prun/blob/c9066d714516c7b6f79dbdbff41c02c24bd9af19/src/refined-prun.css#L1-L15

**Comment by Razenpok** [comment]
Thanks! FYI: in the first message, the link is to a specific commit. Checkout it specifically for a proper repro, as the master branch contains code that has the plugin disabled.

**Comment by coder-layne** [comment]
@Razenpok This plugin performs two time-consuming tasks: 
1. extract resources from CSS files #2 
2. adjust extracted resource addresses based on the importer's output path #14 

These processes require replacing all occurrences of string A with string B. Previously, for Node@14 compatibility, regex was used instead of the built-in `String#replaceAll`, which caused performance issues.

To address this, I will prioritize using the built-in method when supported by the environment.

**Comment by coder-layne** [comment]
@Razenpok I just released v0.5.26 under the next tag, which reduced the build time from 4.86s to 1.79s on my laptop.

**Comment by Razenpok** [comment]
Thank you, sir, it works wonderfully!
